version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run aot-test
      - run: npm run docs
  deploy-docs:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run docs
      - run: npm run docs:deploy
  release:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
      - run: npm run semantic-release

workflows:
  version: 2
  test-n-deploy:
    jobs:
      - test
      - deploy-docs
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
